USE castlelab_market;

ALTER TABLE users ADD COLUMN display_name VARCHAR(80);
ALTER TABLE users ADD COLUMN bio TEXT;
ALTER TABLE users ADD COLUMN university VARCHAR(120);
ALTER TABLE users ADD COLUMN faculty VARCHAR(120);
ALTER TABLE users ADD COLUMN city VARCHAR(80);
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(255);
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE users SET display_name = login WHERE display_name IS NULL;
